# Generated by Django 4.2.3 on 2023-07-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='surename',
            new_name='surname',
        ),
    ]
